import type { Metadata } from "next";
import { Inter, Fira_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});
const fira = Fira_Sans({
	subsets: ["latin", "latin-ext"],
	variable: "--font-fira-sans",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
	style: "italic",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${fira.variable} tracking-tight antialiased`}
			>
				<div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
					<Header />
					<main className="flex min-h-screen flex-col items-center justify-between p-24 grow">
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
